version: "3.9"
services:
  database:
    image: engcadu/assembly-db:latest
    container_name: database
    ports:
      - 5432:5432
  messaging:
    image: rabbitmq:3.9.2-management
    container_name: messaging
    hostname: assembly
    ports:
      - 5672:5672
      - 15672:15672
  app:
    image: engcadu/assembly-app
    container_name: app
    depends_on:
      - database
      - messaging
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
    ports:
      - 8080:8080
